### ISSUE TITLE
dependency missing 

### ISSUE THREAD

**Issue by Uttamdeyjio** [RobertNorthard/distributed-taxi-booking-system-server#4]
can u upload ?

com.robertnorthard.dtms.server.common.DTBSCommon.1.0-SNAPSHOT

**Comment by murthy-sugumar** [comment]
Hi, could you please share the dependency "com.robertnorthard.dtms.server.common.DTBSCommon.1.0-SNAPSHOT" ?

**Comment by RobertNorthard** [comment]
The common library can be found here (https://github.com/RobertNorthard/distributed-taxi-booking-system-common). You will need to build this first to populate your local maven cache.

**Comment by RobertNorthard** [comment]
Closing as per above comment.
